version: '3'

services:
  nginx:
    build:
      context: nginx
    container_name: nginx
    entrypoint: dockerize -wait http://app:4747 -timeout 30s nginx
    command: -g "daemon off;"
    networks:
      - node-network
    ports:
      - 8080:80
    depends_on:
      - app
  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh
    command: bash -c "npm install && node /usr/src/app/index.js"
    networks:
      - node-network
    tty: true
    expose:
      - 4747
    depends_on:
      - db
    volumes:
      - ./node:/usr/src/app
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    tty: true
    command: --innodb-use-native-aio=0
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init-mysql/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    networks:
      - node-network

networks:
  node-network:
    driver: bridge