version: '3'

services:
  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - 8080:80
    depends_on:
      - app
  app:
    build:
      context: node
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    command: node index.js
    expose:
      - 4747
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    tty: true
    command: --innodb-use-native-aio=0
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init-mysql/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    networks:
      - node-network

networks:
  node-network:
    driver: bridge